# This is a basic workflow that is manually triggered

name: Nightly Flatpak build
on: [push, workflow_dispatch]
jobs:
  Build-FLatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: try and install flatpak stuff
        run: sudo apt install flatpak flatpak-builder
      - name: add flathub 
        run: sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - name: install flatpak platform
        run: sudo flatpak install -y org.freedesktop.Sdk/x86_64/21.08
      - name: creating temporary folder
        run: mkdir repo
      - name: do flatpak
        run: bash flatpak_build.sh
      - name: removing temporary folder
        run: sudo rm -rf repo
