# This is a basic workflow that is manually triggered

name: Nightly Flatpak build
on: [push, workflow_dispatch]
jobs:
  Build-FLatpak:
    runs-on: ubuntu-latest
    steps:
      - run: bash -c flatpak_build.sh
