# This is a basic workflow that is manually triggered

name: Nightly Flatpak build
on: [push, workflow_dispatch]
jobs:
  Build-FLatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: try and install flatpak stuff
        run: sudo apt install flatpak flatpak-builder
      - name: do flatpak
        run: |
          bash flatpak_build.sh
